# Site Settings
title: Thiago's Blog
email: thiagopaiva99@gmail.com
description: >- 
  This is a personal blog for post my thinkings.
baseurl: ""
url: ""
github_username:  thiagopaiva99

# Build settings
markdown: kramdown
permalink: /content/:title
theme: minima
plugins:
  - jekyll-feed
