# Site Settings
title: Thiago's Blog
email: thiagopaiva99@gmail.com
description: >- 
  This is a personal blog for post my thinkings.
baseurl: ""
url: ""
github_username:  thiagopaiva99

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
